#%RAML 1.0
title: hc-exp
description: voice bot experience api specification


/healthyme:
  get:
    responses:
      200:
        body:
          text/html:
           
/healthymeresponse:
  get:
    responses:
      200:
        body:
          application/json:
           
/healthymepatient:
  get:
    responses:
      200:
        body:
          application/json:
           
/healthymehospital:
  get:
    responses:
      200:
        body:
          application/json: